version: '3'
services:
  front-end:
    build:
      context: ${PWD}/front-end/
      dockerfile: Dockerfile
    image: front-end
    container_name: front-end
    restart: unless-stopped
    networks:
      - app-network
    
  back-end:
    build:
      context: ${PWD}/back-end/
      dockerfile: Dockerfile
    image: back-end
    container_name: back-end
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - front-end
      - back-end
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email gustavodsf1@gmail.com --agree-tos --no-eff-email --force-renewal -d appmedone.com.br  -d www.appmedone.com.br

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/gustavo/
      o: bind

networks:
  app-network:
    driver: bridge