
version: "3.3"
services:
  front-end:
    build:
      context: ${PWD}/front-end/
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "443:443"
  back-end:
    build:
      context: ${PWD}/back-end/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
