version: '3'
services:
  front-end:
    build:
      context: ${PWD}/front-end/
      dockerfile: Dockerfile
    image: front-end
    container_name: front-end
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - app-network
    depends_on:
      - back-end

  back-end:
    build:
      context: ${PWD}/back-end/
      dockerfile: Dockerfile
    image: back-end
    container_name: back-end
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge